apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nirn-probe
  # Change this to your liking
  namespace: rest-proxy
  labels:
    app: nirn-probe
spec:
  selector:
    matchLabels:
      app: nirn-probe
  template:
    metadata:
      labels:
        app: nirn-probe
    spec:
# Uncomment if you want the probe to run on master nodes
#      tolerations:
#        - key: node-role.kubernetes.io/master
#          effect: NoSchedule
      containers:
        - name: nirn-probe
          image: ghcr.io/germanoeich/nirn-probe:main
          ports:
            - containerPort: 8100
              name: metrics
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LOG_LEVEL
              value: info
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nirn-probe-metrics
  # Change this to your liking
  namespace: rest-proxy
  labels:
    app: nirn-probe
spec:
  ports:
    - name: metrics
      port: 8100
      targetPort: metrics
      protocol: TCP
  selector:
    app: nirn-probe
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nirn-probe-servicemonitor
  # Change this to your liking
  namespace: rest-proxy
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: nirn-probe